services:
    app:
        image: pmconnectgiven/gsd:my-app-1
        deploy:
            replicas: 3
        ports:
            - 3000:3000
        depends_on:
            - mongo
            - redis
        networks:
            - app-net
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: pass
        ports:
            - "27017:27017"
    redis:
        image: redis
        ports:
            - "6379:6379"
networks:
    app-net: