services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: pass
        ports:
            - "27017:27017"
    redis:
        image: redis
        ports:
            - "6379:6379"
